
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramiro Oliveira Pamponet
 */
public class Principal extends javax.swing.JFrame {

    String url = "jdbc:postgresql://192.168.0.2:5432/fciapopular";
    String user = "postgres";
    String senha = "";
    Connection con;
    Statement stm;
    ResultSet rs;
    String receita="1";
    String query;
    String total;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        getRootPane().setDefaultButton(btPesquisar);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gupoTipoReceita = new javax.swing.ButtonGroup();
        btDados = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodfilial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfcodfarmacia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfcidfilial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfrazaosocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfnomefilial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcnpj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfuf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfcep = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfendereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfDataInicial = new javax.swing.JTextField();
        tfDataFinal = new javax.swing.JTextField();
        rbSUS = new javax.swing.JRadioButton();
        rbParticular = new javax.swing.JRadioButton();
        rbTotal = new javax.swing.JRadioButton();
        btPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FPB - Estatistica de Receitas");
        setResizable(false);

        btDados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDados.setText("Mostrar Dados");
        btDados.setFocusable(false);
        btDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDadosActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);

        jLabel1.setText("Código Filial:");

        tfcodfilial.setEditable(false);
        tfcodfilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcodfilial.setFocusable(false);

        jLabel2.setText("Código Farmacia:");

        tfcodfarmacia.setEditable(false);
        tfcodfarmacia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcodfarmacia.setFocusable(false);

        jLabel3.setText("Cidade:");

        tfcidfilial.setEditable(false);
        tfcidfilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcidfilial.setFocusable(false);

        jLabel4.setText("Razão Social:");

        tfrazaosocial.setEditable(false);
        tfrazaosocial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfrazaosocial.setFocusable(false);

        jLabel5.setText("Nome Filial:");

        tfnomefilial.setEditable(false);
        tfnomefilial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfnomefilial.setFocusable(false);

        jLabel6.setText("CNPJ:");

        tfcnpj.setEditable(false);
        tfcnpj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcnpj.setFocusable(false);

        jLabel7.setText("I.E.:");

        tfie.setEditable(false);
        tfie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfie.setFocusable(false);

        jLabel8.setText("UF:");

        tfuf.setEditable(false);
        tfuf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfuf.setFocusable(false);

        jLabel9.setText("CEP:");

        tfcep.setEditable(false);
        tfcep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfcep.setFocusable(false);

        jLabel10.setText("Endereço:");

        tfendereco.setEditable(false);
        tfendereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfendereco.setFocusable(false);

        jLabel11.setText("Bairro:");

        tfbairro.setEditable(false);
        tfbairro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfbairro.setFocusable(false);

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfendereco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfnomefilial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfuf, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcep))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfcodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcodfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcidfilial)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfcodfilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfcodfarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfcidfilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfnomefilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setText("Data Inicial:");
        jLabel12.setFocusable(false);

        jLabel13.setText("Data Final:");
        jLabel13.setFocusable(false);

        jLabel14.setText("Tipo de Receita:");
        jLabel14.setFocusable(false);

        jLabel15.setText("(aaaa-MM-dd)");
        jLabel15.setFocusable(false);

        jLabel16.setText("(aaaa-MM-dd)");
        jLabel16.setFocusable(false);

        tfDataInicial.requestFocus();
        tfDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataInicialActionPerformed(evt);
            }
        });

        tfDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataFinalActionPerformed(evt);
            }
        });

        gupoTipoReceita.add(rbSUS);
        rbSUS.setSelected(true);
        rbSUS.setText("SUS");
        rbSUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSUSActionPerformed(evt);
            }
        });

        gupoTipoReceita.add(rbParticular);
        rbParticular.setText("Particular");
        rbParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParticularActionPerformed(evt);
            }
        });

        gupoTipoReceita.add(rbTotal);
        rbTotal.setText("Total");
        rbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTotalActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btPesquisar))
                    .addComponent(rbParticular)
                    .addComponent(rbSUS))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDataFinal, tfDataInicial});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(rbSUS)
                    .addComponent(tfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbParticular)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTotal)
                    .addComponent(btPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setFocusable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addGap(298, 298, 298))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        setBounds(162, 0, 708, 727);
    }// </editor-fold>//GEN-END:initComponents

    private void btDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDadosActionPerformed
        try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(url, user, senha);
            stm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "select distinct f.cod_filial, f.cod_farmacia,  f.raz_social,  f.nom_filial,  f.num_cnpj,  f.num_inscest,   f.end_filial,   f.bai_filial, f.cid_filial,  f.cep_filial,  f.est_filial from cadfilia f, cadcvend v where v.cod_filial=f.cod_filial";
            rs = stm.executeQuery(sql);
            mostraDados();
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btDadosActionPerformed
    
    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void tfDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataInicialActionPerformed
        tfDataInicial.transferFocus();
    }//GEN-LAST:event_tfDataInicialActionPerformed

    private void tfDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataFinalActionPerformed
        tfDataFinal.transferFocus();
    }//GEN-LAST:event_tfDataFinalActionPerformed
    
    private void rbSUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSUSActionPerformed
        receita = "1";
        if(rbSUS.isSelected());
            receita="1";
        rbSUS.nextFocus();

    }//GEN-LAST:event_rbSUSActionPerformed

    private void rbParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParticularActionPerformed
        receita = "2";
        if(rbParticular.isSelected())
            receita="2";
        rbParticular.nextFocus();

    }//GEN-LAST:event_rbParticularActionPerformed

    private void rbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTotalActionPerformed
        receita = "3";
        if(rbTotal.isSelected())
            receita="3";
        rbTotal.nextFocus();

    }//GEN-LAST:event_rbTotalActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        StringWriter sw = new StringWriter();
        PrintWriter out = new PrintWriter(sw);
        try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(url, user, senha);
            Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            if (receita.equals("1") || receita.equals("2")) {
                query = "select distinct(dat_emissao), count(flg_receita) from cadcvend where "
                        + "dat_emissao between '" + tfDataInicial.getText() + "' and '" + tfDataFinal.getText() + "' and flg_receita='" + receita + "' and flg_excluido is null "
                        + "group by dat_emissao order by dat_emissao";

                total = "select count(flg_receita) from cadcvend where dat_emissao between '" + tfDataInicial.getText() + "' "
                        + "and '" + tfDataFinal.getText() + "' and flg_receita='" + receita + "' and flg_excluido is null";
            } else if (receita.equals("3")) {
                query = "select distinct(dat_emissao), count(flg_receita) from cadcvend where "
                        + "dat_emissao between '" + tfDataInicial.getText() + "' and '" + tfDataFinal.getText() + "' and flg_receita is not null and flg_excluido is null "
                        + "group by dat_emissao order by dat_emissao";

                total = "select count(flg_receita) from cadcvend where dat_emissao between '" + tfDataInicial.getText() + "' "
                        + "and '" + tfDataFinal.getText() + "' and flg_receita is not null and flg_excluido is null";

            }
            ResultSet rst = stmt.executeQuery(query);

            if (rst.first()) {

                if (receita.equals("1")) {
                    out.println("");
                    out.println("\tReceitas SUS");
                    out.println("\tData\t\tQuantidade");
                    out.println("\t------------------------------------------------------");
                    out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    while (rst.next()) {
                        out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    }
                    out.println("\t------------------------------------------------------");
                    ResultSet result = stmt.executeQuery(total);
                    if (result.first()) {
                        out.println("\tTotal de Receitas SUS: " + result.getInt("count"));
                        con.close();
                    }
                } else if (receita.equals("2")) {
                    out.println("");
                    out.println("\tReceitas Particulares");
                    out.println("\tData\t\tQuantidade");
                    out.println("\t------------------------------------------------------");
                    out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    while (rst.next()) {
                        out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    }
                    out.println("\t------------------------------------------------------");
                    ResultSet result = stmt.executeQuery(total);
                    if (result.first()) {
                        out.println("\tTotal de Receitas Particulares: " + result.getInt("count"));
                        con.close();
                    }
                } else if (receita.equals("3")) {
                    out.println("");
                    out.println("\tTotal de Receitas");
                    out.println("\tData\t\tQuantidade");
                    out.println("\t------------------------------------------------------");
                    out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    while (rst.next()) {
                        out.println("\t"+rst.getString("dat_emissao") + "\t\t" + rst.getInt("count"));
                    }
                    out.println("\t------------------------------------------------------");
                    ResultSet result = stmt.executeQuery(total);
                    if (result.first()) {
                        out.println("\tTotal de Receitas SUS e Particulares: " + result.getInt("count"));
                        con.close();
                    }
                } else {
                    out.println("\tNão Consegui Pegar os Dados!");
                }

            } else {
                out.println("\tNão Foi possivel localizar os dados");
            }

        } catch (ClassNotFoundException e) {
            out.println("\t"+e.getMessage());

        } catch (SQLException e) {
            out.println("\t"+e.getMessage());
        }
        jTextArea1.append(sw.toString());
    }//GEN-LAST:event_btPesquisarActionPerformed
    
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfDataInicial.setText("");
        tfDataFinal.setText("");
        jTextArea1.setText("");
        tfDataInicial.requestFocus();
        rbSUS.setSelected(true);
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
            
    }

    private void mostraDados() throws SQLException {
        if (rs.first()) {
            tfcodfilial.setText(rs.getString("cod_filial"));
            tfcodfarmacia.setText(rs.getString("cod_farmacia"));
            tfrazaosocial.setText(rs.getString("raz_social"));
            tfnomefilial.setText(rs.getString("nom_filial"));
            tfcnpj.setText(rs.getString("num_cnpj"));
            tfie.setText(rs.getString("num_inscest"));
            tfendereco.setText(rs.getString("end_filial"));
            tfbairro.setText(rs.getString("bai_filial"));
            tfcidfilial.setText(rs.getString("cid_filial"));
            tfcep.setText(rs.getString("cep_filial"));
            tfuf.setText(rs.getString("est_filial"));
        } else {
            JOptionPane.showMessageDialog(null, "Não Localizou Dados!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDados;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup gupoTipoReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbParticular;
    private javax.swing.JRadioButton rbSUS;
    private javax.swing.JRadioButton rbTotal;
    private javax.swing.JTextField tfDataFinal;
    private javax.swing.JTextField tfDataInicial;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfcep;
    private javax.swing.JTextField tfcidfilial;
    private javax.swing.JTextField tfcnpj;
    private javax.swing.JTextField tfcodfarmacia;
    private javax.swing.JTextField tfcodfilial;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JTextField tfie;
    private javax.swing.JTextField tfnomefilial;
    private javax.swing.JTextField tfrazaosocial;
    private javax.swing.JTextField tfuf;
    // End of variables declaration//GEN-END:variables
}